version: '3.8'

services:
  app:
    build: .
    container_name: api-flask
    restart: always
    environment:
      - DB_HOST=servidor-bd-ejemplo
      - DB_USER=user_app
      - DB_PASSWORD=secure_password
      - DB_NAME=app_db
    depends_on:
      - servidor-bd-ejemplo
    networks:
      - app-net

  servidor-bd-ejemplo:
    image: mysql:8.0
    container_name: servidor-bd-ejemplo
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: app_db
      MYSQL_USER: user_app
      MYSQL_PASSWORD: secure_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-net

  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  mysql_data: